"""
Django settings for s1 project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!yl9v_ilxp=)03x8%s!x%wvl30(yo38za0^3u#n*9kg*-kzvt5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'modules.city_tales',
    'modules.city_routes',
    'django.contrib.gis',
    'modules.gov_connect',
    'django.contrib.gis',
    'modules.feedback',
    'channels',
    'modules.feedback',
    'modules.hot_news',
    'modules.community_hub',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 's1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 's1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CITY_TALES_CONFIG = {
    'QR_CODE_SIZE': 300,
    'AUDIO_MAX_DURATION': 300,  # секунд
    'DEFAULT_LOCATION': '40.5200,72.8000'  # Координаты Баткена
}

CITY_ROUTES_CONFIG = {
    'DEFAULT_MAP_PROVIDER': 'osm',
    'SMS_ENABLED': True,
    'MAX_ROUTE_POINTS': 100,
    'VEHICLE_UPDATE_INTERVAL': 30  # seconds
}

GOV_CONNECT_CONFIG = {
    'DEFAULT_DEPARTMENTS': [
        'road_services',
        'utilities',
        'emergency'
    ],
    'AUTO_ASSIGN_COMPLAINTS': True,
    'NOTIFICATION_METHODS': ['email', 'sms'],
    'MAX_COMPLAINT_PHOTO_SIZE': 5  # MB
}

COMMUNITY_HUB_CONFIG = {
    'MAX_MEMBERS_PER_COMMUNITY': 5000,
    'DEFAULT_REPUTATION_GAIN': 1,
    'REALTIME_CHAT_ENABLED': True,
    'MODERATION_REQUIRED': False
}

FEEDBACK_CONFIG = {
    'MIN_REVIEW_LENGTH': 20,
    'MAX_REVIEW_LENGTH': 2000,
    'PROFANITY_FILTER': True,
    'AUTO_APPROVE_THRESHOLD': 4,  # Автоодобрение отзывов с рейтингом >=4
    'RATING_UPDATE_INTERVAL': 3600  # Обновление рейтингов каждый час
}

HOT_NEWS_CONFIG = {
    'RSS_FEEDS': [
        'https://example.com/news/rss',
        'https://government.kg/feed'
    ],
    'EMERGENCY_ALERT_THRESHOLD': 'high',
    'AUTO_VERIFY_SOURCES': ['government.kg'],
    'DEFAULT_TIMEZONE': 'Asia/Bishkek'
}

HEALTH_CONNECT_CONFIG = {
    'EMERGENCY_RESPONSE_TIME': 5,  # минут
    'VIDEO_CONSULTATION': True,
    'ALLOWED_FILE_TYPES': ['pdf', 'dicom', 'jpg'],
    'DATA_RETENTION_YEARS': 10,
    'HL7_INTEGRATION': {
        'ENABLED': True,
        'ENDPOINT': 'hl7://hospital:5000'
    }
}

# settings.py
MADE_IN_BATKEN_CONFIG = {
    'MIN_GROUP_PURCHASE': 10,
    'MAX_AUCTION_DURATION_DAYS': 7,
    'COMMISSION_RATE': 0.05,
    'ALLOWED_SELLER_TYPES': ['individual', 'legal_entity'],
    'DELIVERY_OPTIONS': ['courier', 'pickup'],
    'LOCAL_CURRENCY': 'KGS'
}
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
