"""
Django settings for s1 project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
import venv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!yl9v_ilxp=)03x8%s!x%wvl30(yo38za0^3u#n*9kg*-kzvt5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition
LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (40.1234, 72.3456),
    'DEFAULT_ZOOM': 13,
    'MIN_ZOOM': 10,
    'MAX_ZOOM': 18,
    'RESET_VIEW': False,
    'SCALE': 'metric',
    'ATTRIBUTION_PREFIX': 'GIS Раззаков'
}

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'modules.city_tales',
    'modules.city_routes',
    'django.contrib.gis',
    'modules.gov_connect',
    'modules.feedback',
    'channels',
    'modules.feedback',
    'modules.hot_news',
    'modules.community_hub',
    'modules.city_routes',
    'rest_framework',
    'city_routes.apps.CityRoutesConfig',
    'city_tales.apps.CityTalesConfig',
    'drf_spectacular',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'presentation/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': venv('DB_NAME'),
        'USER': venv('DB_USER'),
        'PASSWORD': venv('DB_PASSWORD'),
        'HOST': venv('DB_HOST', default='localhost'),
        'PORT': venv('DB_PORT', default='5432'),
        'OPTIONS': {
            'connect_timeout': 5,  # 5 seconds timeout
            'sslmode': venv('DB_SSL_MODE', default='prefer'),
            'application_name': 'smartcity_backend',
        },
        'CONN_MAX_AGE': 600,  # Persistent connections
        'DISABLE_SERVER_SIDE_CURSORS': False,  # For large GIS datasets
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Bishkek'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

ADMIN_SITE_HEADER = "City Tales Administration"
ADMIN_SITE_TITLE = "City Tales Admin Portal"



MEDIA_PROCESSING = {
    'VOSK_MODEL_PATH': os.path.join(BASE_DIR, 'models/vosk'),
    'MAX_VIDEO_SIZE_MB': 500,
    'DEFAULT_LANGUAGE': 'ru'
}


# Настройки сжатия и проверки целостности
COMPRESSION_LEVEL = 6  # По умолчанию
PREFERRED_HASH_ALGORITHM = 'sha256'  # Для проверки файлов


OFFLINE_API_BASE_URL = 'https://api.citytales.example.com/v1'
OFFLINE_CACHE_TIMEOUT = 60 * 60 * 24  # 24 часа
API_KEY = 'your-secret-key'


CACHES = {
    'offline': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
        }
    }
}



# Настройки обработки медиа
AUDIO_BITRATE = '128k'  # Целевой битрейт аудио
IMAGE_QUALITY = 85      # Качество сжатия изображений (1-100)
OFFLINE_STORAGE = 'offline_packages'  # Папка для офлайн-пакетов
QR_LOGO_PATH = os.path.join(BASE_DIR, 'static/logo.png')  # Для брендированных QR



CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", 6379)],
        },
    },
}




ELASTIC_CONFIG = {
    "hosts": ["http://elasticsearch:9200"],
    "community_index": "communities",
    "event_index": "events",
    "user_index": "users"
}


REST_FRAMEWORK = {
    # Authentication
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',  # OAuth2
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # JWT
        'rest_framework.authentication.SessionAuthentication',  # Browser UI
    ],

    # Permission Policies
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],

    # Request Handling
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',  # For file uploads
    ],

    # Response Formatting
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'core.api.renderers.BrowsableAPIRendererNoForms',  # Custom UI renderer
    ],

    # Filtering & Search
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],

    # Pagination
    'DEFAULT_PAGINATION_CLASS': 'core.api.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': 50,

    # Throttling (Rate Limiting)
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'core.api.throttling.BurstRateThrottle',  # Custom
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
        'burst': '60/minute',  # For emergency APIs
    },

    # Versioning
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
    'ALLOWED_VERSIONS': ['v1', 'v2'],

    # Schema Generation
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    # Exception Handling
    'EXCEPTION_HANDLER': 'core.api.exceptions.custom_exception_handler',

    # Datetime Formatting
    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S%z',
    'DATE_FORMAT': '%Y-%m-%d',
    'TIME_FORMAT': '%H:%M:%S',
}

CITY_TALES_CONFIG = {
    'QR_CODE_SIZE': 300,
    'AUDIO_MAX_DURATION': 300,  # секунд
    'DEFAULT_LOCATION': '40.5200,72.8000'  # Координаты Баткена
}

CITY_ROUTES_CONFIG = {
    'DEFAULT_MAP_PROVIDER': 'osm',
    'SMS_ENABLED': True,
    'MAX_ROUTE_POINTS': 100,
    'VEHICLE_UPDATE_INTERVAL': 30,# seconds
    'MAP_PROVIDER': 'mapbox',  # или 'osm', 'google'
    'CACHE_ENABLED': True,
    'DEFAULT_LANGUAGE': 'ru'
}

CITY_ROUTES_OPTIMIZATIONS = {
    'ROUTE_CACHING': True,    # Кеширование маршрутов
    'BATCH_PROCESSING': True, # Пакетная обработка
    'PRELOAD_HOT_ROUTES': 10  # Предзагрузка топ-10 маршрутов
}

GOV_CONNECT_CONFIG = {
    'DEFAULT_DEPARTMENTS': [
        'road_services',
        'utilities',
        'emergency'
    ],
    'AUTO_ASSIGN_COMPLAINTS': True,
    'NOTIFICATION_METHODS': ['email', 'sms'],
    'MAX_COMPLAINT_PHOTO_SIZE': 5  # MB
}

COMMUNITY_HUB_CONFIG = {
    'MAX_MEMBERS_PER_COMMUNITY': 5000,
    'DEFAULT_REPUTATION_GAIN': 1,
    'REALTIME_CHAT_ENABLED': True,
    'MODERATION_REQUIRED': False
}

FEEDBACK_CONFIG = {
    'MIN_REVIEW_LENGTH': 20,
    'MAX_REVIEW_LENGTH': 2000,
    'PROFANITY_FILTER': True,
    'AUTO_APPROVE_THRESHOLD': 4,  # Автоодобрение отзывов с рейтингом >=4
    'RATING_UPDATE_INTERVAL': 3600  # Обновление рейтингов каждый час
}

HOT_NEWS_CONFIG = {
    'RSS_FEEDS': [
        'https://example.com/news/rss',
        'https://government.kg/feed'
    ],
    'EMERGENCY_ALERT_THRESHOLD': 'high',
    'AUTO_VERIFY_SOURCES': ['government.kg'],
    'DEFAULT_TIMEZONE': 'Asia/Bishkek'
}

HEALTH_CONNECT_CONFIG = {
    'EMERGENCY_RESPONSE_TIME': 5,  # минут
    'VIDEO_CONSULTATION': True,
    'ALLOWED_FILE_TYPES': ['pdf', 'dicom', 'jpg'],
    'DATA_RETENTION_YEARS': 10,
    'HL7_INTEGRATION': {
        'ENABLED': True,
        'ENDPOINT': 'hl7://hospital:5000'
    }
}

# settings.py
MADE_IN_BATKEN_CONFIG = {
    'MIN_GROUP_PURCHASE': 10,
    'MAX_AUCTION_DURATION_DAYS': 7,
    'COMMISSION_RATE': 0.05,
    'ALLOWED_SELLER_TYPES': ['individual', 'legal_entity'],
    'DELIVERY_OPTIONS': ['courier', 'pickup'],
    'LOCAL_CURRENCY': 'KGS'
}

CITY_ROUTES = {
    'MAP_PROVIDER': 'osm',  # OpenStreetMap
    'MAX_ROUTE_POINTS': 100,
    'REALTIME_UPDATE_INTERVAL': 30,  # секунд
}

LOGGING = {
    'version': 1,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/var/log/cityroutes.log',
        },
    },
    'loggers': {
        'cityroutes': {
            'handlers': ['file'],
            'level': 'DEBUG',
        },
    },
}
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


QR_DEFAULT_PARAMS = {
    'utm_source': 'qr_code',
    'utm_medium': 'print',
    'utm_campaign': 'city_tales'
}